# -*- mode: ruby -*-
# vi: set ft=ruby :
#

LINUX_BASE_BOX = "bento/ubuntu-18.04"
LINUX_IP_ADDRESS = "192.168.56.200"

Vagrant.configure(2) do |config|
	dcPrimary = "dc1"
	dcSecondary = "dc2"
	serverName = "consul-server"
	serverName2 = "consul-server-2"
	databaseName = "postgres"
	productName = "product-api"
	publicName = "public-api"
	frontendName = "frontend"
	serverIP = "192.168.56.10"
	serverIP2 = "192.168.56.110"
	databaseIP = "192.168.56.20"
	productIP = "192.168.56.30"
	publicIP = "192.168.56.40"
	frontendIP = "192.168.56.50"

	#cart
	cartIp = "192.168.56.60"
	cartName = "cart"

	#order
	orderIp = "192.168.56.65"
	orderName = "order"

	#ingress gateway
	ingressServerName = "ingress"
	ingressServerIP = "192.168.56.15"

	#mesh gateway
	meshServerName = "mesh"
	meshServerIP = "192.168.56.12"
	meshName = "gateway-primary"

	#mesh gateway 2
	meshServerName2 = "mesh2"
	meshServerIP2 = "192.168.56.112"
	meshName2 = "gateway-secondary"

	config.vm.define serverName, autostart: true, primary: true do |vmCfg|
		vmCfg.vm.box = LINUX_BASE_BOX
		vmCfg.vm.hostname = serverName
		vmCfg = configureProviders(vmCfg)
		vmCfg = configureLinuxProvisioners(vmCfg)
		vmCfg = configurePrometheusProvisioners(vmCfg)

		vmCfg.vm.provider "virtualbox" do |_|
			vmCfg.vm.network :private_network, ip: serverIP
			vmCfg.vm.network :forwarded_port, guest: 22, host: 2222, disabled: true
			vmCfg.vm.network :forwarded_port, guest: 8500, host: 8500
			vmCfg.vm.network :forwarded_port, guest: 9090, host: 9090
		end

		vmCfg.vm.synced_folder './config', '/mnt/my-machine'

		vmCfg.vm.provision "shell",
			privileged: true,
			path: './scripts/consul-server.sh',
			args: [serverIP]
	end

	#ingress 1
	config.vm.define ingressServerName, autostart: true, primary: false do |vmCfg|
		vmCfg.vm.box = LINUX_BASE_BOX
		vmCfg.vm.hostname = ingressServerName
		vmCfg = configureProviders(vmCfg)
		vmCfg = configureLinuxProvisioners(vmCfg)
		vmCfg = configureIngressProvisioners(vmCfg, serverIP, ingressServerName, ingressServerIP)

		vmCfg.vm.provider "virtualbox" do |_|
			vmCfg.vm.network :private_network, ip: ingressServerIP
			vmCfg.vm.network :forwarded_port, guest: 22, host: 2222, disabled: true
		end

		vmCfg.vm.synced_folder './config', '/mnt/my-machine'

	end

	#mesh 1
	config.vm.define meshServerName, autostart: true, primary: false do |vmCfg|
		vmCfg.vm.box = LINUX_BASE_BOX
		vmCfg.vm.hostname = meshServerName
		vmCfg = configureProviders(vmCfg)
		vmCfg = configureLinuxProvisioners(vmCfg)
		vmCfg = configureMeshGatewayProvisioners(vmCfg, serverIP, meshServerName, meshServerIP, meshName, dcPrimary)

		vmCfg.vm.provider "virtualbox" do |_|
			vmCfg.vm.network :private_network, ip: meshServerIP
			vmCfg.vm.network :forwarded_port, guest: 22, host: 2222, disabled: true
		end

		vmCfg.vm.synced_folder './config', '/mnt/my-machine'

	end

	#mesh 2
	config.vm.define meshServerName2, autostart: true, primary: false do |vmCfg|
		vmCfg.vm.box = LINUX_BASE_BOX
		vmCfg.vm.hostname = meshServerName2
		vmCfg = configureProviders(vmCfg)
		vmCfg = configureLinuxProvisioners(vmCfg)
		vmCfg = configureMeshGatewayProvisioners(vmCfg, serverIP2, meshServerName2, meshServerIP2, meshName2, dcSecondary)

		vmCfg.vm.provider "virtualbox" do |_|
			vmCfg.vm.network :private_network, ip: meshServerIP2
			vmCfg.vm.network :forwarded_port, guest: 22, host: 2222, disabled: true
		end

		vmCfg.vm.synced_folder './config', '/mnt/my-machine'

	end

	#consul 2
	config.vm.define serverName2, autostart: true, primary: true do |vmCfg|
		vmCfg.vm.box = LINUX_BASE_BOX
		vmCfg.vm.hostname = serverName2
		vmCfg = configureProviders(vmCfg)
		vmCfg = configureLinuxProvisioners(vmCfg)
		vmCfg = configurePrometheusProvisioners(vmCfg)

		vmCfg.vm.provider "virtualbox" do |_|
			vmCfg.vm.network :private_network, ip: serverIP2
			vmCfg.vm.network :forwarded_port, guest: 22, host: 2222, disabled: true
			vmCfg.vm.network :forwarded_port, guest: 8500, host: 18500
			vmCfg.vm.network :forwarded_port, guest: 9090, host: 19090
		end

		vmCfg.vm.synced_folder './config', '/mnt/my-machine'

		vmCfg.vm.provision "shell",
			privileged: true,
			path: './scripts/consul-server-2.sh',
			args: [serverIP, meshServerIP + ":8443"]
	end

	#cart
	config.vm.define cartName, autostart: true, primary: false do |vmCfg|
		vmCfg.vm.box = LINUX_BASE_BOX
		vmCfg.vm.hostname = cartName
		vmCfg = configureProviders(vmCfg)
		vmCfg = configureLinuxProvisioners(vmCfg)
		vmCfg = configureConsulClientProvisioners(vmCfg, serverIP, cartName, cartIp, dcPrimary)

		vmCfg.vm.provider "virtualbox" do |_|
			vmCfg.vm.network :private_network, ip: cartIp
			vmCfg.vm.network :forwarded_port, guest: 22, host: 2222, disabled: true
		end

		vmCfg.vm.synced_folder './config', '/mnt/my-machine'

		vmCfg.vm.provision "shell",
			privileged: true,
			path: './scripts/fake-service.sh',
			args: [cartName]
	end

	#order
	config.vm.define orderName, autostart: true, primary: false do |vmCfg|
		vmCfg.vm.box = LINUX_BASE_BOX
		vmCfg.vm.hostname = orderName
		vmCfg = configureProviders(vmCfg)
		vmCfg = configureLinuxProvisioners(vmCfg)
		vmCfg = configureConsulClientProvisioners(vmCfg, serverIP, orderName, orderIp, dcPrimary)

		vmCfg.vm.provider "virtualbox" do |_|
			vmCfg.vm.network :private_network, ip: orderIp
			vmCfg.vm.network :forwarded_port, guest: 22, host: 2222, disabled: true
		end

		vmCfg.vm.synced_folder './config', '/mnt/my-machine'

		vmCfg.vm.provision "shell",
			privileged: true,
			path: './scripts/fake-service.sh',
			args: [orderName]
	end

	#database
	config.vm.define databaseName, autostart: true, primary: false do |vmCfg|
		vmCfg.vm.box = LINUX_BASE_BOX
		vmCfg.vm.hostname = databaseName
		vmCfg = configureProviders(vmCfg)
		vmCfg = configureLinuxProvisioners(vmCfg)
		vmCfg = configureConsulClientProvisioners(vmCfg, serverIP, databaseName, databaseIP, dcPrimary)

		vmCfg.vm.provider "virtualbox" do |_|
			vmCfg.vm.network :private_network, ip: databaseIP
		end

		vmCfg.vm.synced_folder './config', '/mnt/my-machine'

		vmCfg.vm.provision "shell",
			privileged: true,
			path: './scripts/fake-service.sh'
	end

	config.vm.define productName, autostart: true, primary: false do |vmCfg|
		vmCfg.vm.box = LINUX_BASE_BOX
		vmCfg.vm.hostname = productName
		vmCfg = configureProviders(vmCfg)
		vmCfg = configureLinuxProvisioners(vmCfg)
		vmCfg = configureConsulClientProvisioners(vmCfg, serverIP, productName, productIP, dcPrimary)

		vmCfg.vm.provider "virtualbox" do |_|
			vmCfg.vm.network :private_network, ip: productIP
		end

		vmCfg.vm.synced_folder './config', '/mnt/my-machine'

		vmCfg.vm.provision "shell",
			privileged: true,
			path: './scripts/product-api.sh'
	end

	config.vm.define publicName, autostart: true, primary: false do |vmCfg|
		vmCfg.vm.box = LINUX_BASE_BOX
		vmCfg.vm.hostname = publicName
		vmCfg = configureProviders(vmCfg)
		vmCfg = configureLinuxProvisioners(vmCfg)
		vmCfg = configureConsulClientProvisioners(vmCfg, serverIP, publicName, publicIP, dcPrimary)

		vmCfg.vm.provider "virtualbox" do |_|
			vmCfg.vm.network :private_network, ip: publicIP
		end

		vmCfg.vm.synced_folder './config', '/mnt/my-machine'

		vmCfg.vm.provision "shell",
			privileged: true,
			path: './scripts/public-api.sh'
	end

	config.vm.define frontendName, autostart: true, primary: false do |vmCfg|
		vmCfg.vm.box = LINUX_BASE_BOX
		vmCfg.vm.hostname = frontendName
		vmCfg = configureProviders(vmCfg)
		vmCfg = configureLinuxProvisioners(vmCfg)
		vmCfg = configureConsulClientProvisioners(vmCfg, serverIP, frontendName, frontendIP, dcPrimary)

		vmCfg.vm.provider "virtualbox" do |_|
			vmCfg.vm.network :private_network, ip: frontendIP
			vmCfg.vm.network :forwarded_port, guest: 80, host: 8000
		end

		vmCfg.vm.synced_folder './config', '/mnt/my-machine'

		vmCfg.vm.provision "shell",
			privileged: true,
			path: './scripts/frontend.sh'
	end
end

def configureLinuxProvisioners(vmCfg)
	vmCfg.vm.provision "shell",
		privileged: true,
		inline: 'rm -f /home/vagrant/linux.iso'

	vmCfg.vm.provision "shell",
		privileged: true,
		path: './scripts/vagrant-linux-priv-config.sh'

	vmCfg.vm.provision "shell",
		privileged: true,
		path: './scripts/vagrant-linux-priv-consul.sh'

	return vmCfg
end

def configurePrometheusProvisioners(vmCfg)
	vmCfg.vm.provision "shell",
		privileged: true,
		path: './scripts/vagrant-linux-priv-prometheus.sh'

	vmCfg.vm.provision "shell",
		privileged: true,
		path: './scripts/prometheus-server.sh'

	return vmCfg
end

def configureConsulClientProvisioners(vmCfg, serverIP, appName, clientIP, dcName)
	vmCfg.vm.provision "shell",
		privileged: true,
		path: './scripts/vagrant-linux-priv-envoy.sh'

	vmCfg.vm.provision "shell",
		privileged: true,
		path: './scripts/consul-client.sh',
		args: [serverIP, appName, clientIP, dcName]

	return vmCfg
end

def configureIngressProvisioners(vmCfg, serverIP, appName, clientIP)
	vmCfg.vm.provision "shell",
		privileged: true,
		path: './scripts/vagrant-linux-priv-envoy.sh'

	vmCfg.vm.provision "shell",
		privileged: true,
		path: './scripts/consul-ingress.sh',
		args: [serverIP, appName, clientIP]

	return vmCfg
end

def configureMeshGatewayProvisioners(vmCfg, serverIP, appName, clientIP, meshName, dcName)
	vmCfg.vm.provision "shell",
		privileged: true,
		path: './scripts/vagrant-linux-priv-envoy.sh'

	vmCfg.vm.provision "shell",
		privileged: true,
		path: './scripts/consul-mesh-gateway.sh',
		args: [serverIP, appName, clientIP, meshName, dcName]

	return vmCfg
end

def configureProviders(vmCfg, cpus: "1", memory: "512")
	vmCfg.vm.provider "virtualbox" do |v|
		v.customize ["modifyvm", :id, "--cableconnected1", "on"]
		v.memory = memory
		v.cpus = cpus
	end

	["vmware_fusion", "vmware_workstation"].each do |p|
		vmCfg.vm.provider p do |v|
			v.enable_vmrun_ip_lookup = false
			v.vmx["memsize"] = memory
			v.vmx["numvcpus"] = cpus
		end
	end

	vmCfg.vm.provider "virtualbox" do |v|
		v.customize ["modifyvm", :id, "--cableconnected1", "on", "--audio", "none"]
		v.memory = memory
		v.cpus = cpus
	end

	return vmCfg
end
